# Generated by Django 4.2.3 on 2023-07-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0002_land_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
