# Generated by Django 4.2.3 on 2023-07-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0004_alter_land_acreage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='acreage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='land',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
