# Generated by Django 4.2.3 on 2023-07-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lands', '0005_alter_land_acreage_alter_land_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
