version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: hayden
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: